### ISSUE TITLE
Instead of using an environment variable, which doesn't persist, have the token set in a JSON file ({token: <token>}) and loaded with require()

### ISSUE THREAD

**Issue by Unihedro** [endrawes0/Chesster#1]

**Comment by endrawes0** [comment]
Are you suggesting then that we have a single JSON config file per installation of the bot and configure it based on the JSON?

If so, I think this is a great suggestion!

Ill let you know when I have implemented it.

**Comment by endrawes0** [comment]
This is fixed and will be released in the next rollout.

Thank you for the suggestion.

**Comment by Unihedro** [comment]
:+1:
