### ISSUE TITLE
Incorrect date conversion for notifications

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#102]
I am UTC-6, but I got this notification today:
```forhavu vs r-mena has been scheduled for 2016-07-06 @ 11:00 UTC, which is Wed @ 13:00 for you.```

Which is (for some reason) converting it it to UTC+2 !? I have tested locally and it's converting properly for me when testing locally. Note that the notification I got for my own game was also incorrect.

``` mooserohde vs lakinwecker has been scheduled for 2016-07-10 @ 20:00 UTC, which is Sun @ 22:00 for you.```

**Comment by endrawes0** [comment]
Note, I got the same update from chesster - which is strange BC we are diff time zones:

` mooserohde vs lakinwecker has been scheduled for 2016-07-10 @ 20:00 UTC, which is Sun @ 22:00 for you. `

Did the formatter get called once or many times? I seem to recall seeing it called only once and then reused.

I could be mistaken.
