### ISSUE TITLE
Remind me 15 minutes before a-game-starts for ...

### ISSUE THREAD

**Issue by endrawes0** [endrawes0/Chesster#106]
We have a request to set up events and subscriptions prior to the link being posted. Not sure what the language would look like but rather than basing the event on the game link, wet would base it on the pairing schedule. 

Will require a system to monitor scheduled events and emit. 

I'll be thinking about the best way to do this.

**Comment by lakinwecker** [comment]
We could add 4 events:

`tell me when its-15-minutes-before-a-game in 45+45 for lakinwecker`
`tell me when its-30-minutes-before-a-game in 45+45 for lakinwecker`
`tell me when its-45-minutes-before-a-game in 45+45 for lakinwecker`
`tell me when its-60-minutes-before-a-game in 45+45 for lakinwecker`

And have a timer that runs on the quarter hours that generates these events.

**Comment by endrawes0** [comment]
That's essentially what was thinking but I like the language you chose.

**Comment by lakinwecker** [comment]
The website sends a message 1 hour before a game starts. I believe this is also superfluous.
