### ISSUE TITLE
Make a 'match summary' type command

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#111]
It should (based on who is asking, or a specific team name) tell you the current score and then give you a listing of all of the pairings and their results or schedule.

I think it should be sorted by time, so that before any matches are played it's a schedule of the match.

@narud suggested this format:
```
Round 1 Parings:        ​*Match Score:    4-1 in our favor*​

Board 1:  W:  @hetraie        B:  mhavgar (Knoddel)        ​*1-0*​
Board 2:  W:  Knoddel         B:  @bloodyfox               ​*1-0*​
Board 3:  W:  @narud          B:  riemannn                 ​*1-0*​
Board 4:  W:  daveyjones01    B:  @thephobia               ​*0-1*​         
Board 5:  W:  @tworivers      B:  elixr                    7/10 @ 02:00                      
Board 6:  W:  pawnsac101      B:  @derked                  ​*0-1*​
```

**Comment by endrawes0** [comment]
This doesn't really give us anything the sheets can't. I'm tempted to reject this feature request.

Any compelling reason I'm missing to keep it?

**Comment by lakinwecker** [comment]
The sheets are hard to use on a phone.  That's the primary difference I see.

**Comment by lakinwecker** [comment]
Also, the sheets are ordered by board, not by date. Which is another thing that I find useful about something like this.

**Comment by endrawes0** [comment]
Fair enough. It is spared.

**Comment by endrawes0** [comment]
Website should make this easier. 

e.g.
https://www.lichess4545.com/team4545/season/4/pairings/team/8/

I think we can close this.

**Comment by endrawes0** [comment]
reopen if you disagree.
