### ISSUE TITLE
Make a Lichess45+45 and a Lonewolf TV page

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#14]
Do it after the gamelink parsing is finished.

**Comment by Unihedro** [comment]
＾＾＾＾＾＾＾＾＾＾＾＾＾

**Comment by endrawes0** [comment]
Can I claim this? In very interested in working on it.

**Comment by endrawes0** [comment]
I'm*

**Comment by lakinwecker** [comment]
Yeah, it's all yours.  I'm not sure if lichess lets you do it though. You might have to ask their developers how to embed a live (arbitrary) game into another webpage.  You can embed some of their other "TV" games into a webpage, but I haven't see a way to to it for any game. 

Also, you'll need a place to publish the HTML page you make - which I can help you setup.

**Comment by endrawes0** [comment]
I reached out to Thibault to ask him about options. We will see if/when he responds.

I'm not sure what/how the live renders are generated. It will certainly come down to that.

**Comment by endrawes0** [comment]
Status update:

I have a reasonable client side started. It will use https://github.com/ornicar/chessground for client side rendering and websockets to communicate with the service.

Some issues with the lichess api need to be worked out, but I will give this some focus soon.

**Comment by endrawes0** [comment]
I have had 0 free time to develop anything in the last month and I don't really see that changing.

If someone else wants to work on this, they should.

**Comment by endrawes0** [comment]
https://www.lichess4545.com/team4545//tv/
https://www.lichess4545.com/lonewolf/tv/
exist
