### ISSUE TITLE
update the @chesster: mods command

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#145]
Add a small sentence about the fact that mods are not notified with this command, and that if you want to notify the mods use: `@chesster: summon mods`

Also, I wonder if this command could be built to identify which mods are online or not and list them that way:

45+45 mods: endrawes0 (**online**), seb32 (**online**), tnan123 (**online**), angborxley (_offline_), prune2000 (_offline_), theino (_offline_), mkoga (_offline_), mrlegilimens (_offline_), petruchio (_offline_)

**Comment by lakinwecker** [comment]
asdfasdfadsf

**Comment by endrawes0** [comment]
we should get a green dot for online people

**Comment by endrawes0** [comment]
first part of this is complete

**Comment by lakinwecker** [comment]
I've rethought this. Identifying the mods which are online will only serve to encourage people to bypass the summon and contact people directly. Closing.
