### ISSUE TITLE
make a my pairings command

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#15]
It should start a DM and it should tell you both of your pairings, their rating, your scheduled times and/or results and perhaps a "countdown" till your game time:

example:

```
Lonewolf: you play endrawes0 (1687) on Sunday at 17:00 which is in 2day, and 3 hours.
Team: You played jaivl (1987) on Saturday at 08:00 and lost.
```

**Comment by endrawes0** [comment]
Yeah, I actually had this in my personal to-do list already.

Good ideas here. I was going to do something simpler but this is good.
