### ISSUE TITLE
Allow mods to update anything

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#18]
Allow mods to update anything

**Comment by lakinwecker** [comment]
This is done for the results and scheduling - which was the only ones that I know of. Were there more? If not, we can close this.

**Comment by endrawes0** [comment]
Game links were already mutable for everyone, correct?

**Comment by lakinwecker** [comment]
That is correct.

**Comment by endrawes0** [comment]
Closed!
