### ISSUE TITLE
fix syntax for available/unavailable help message

### ISSUE THREAD

**Issue by tnan123** [endrawes0/Chesster#180]
probably helpful to also list it under the available commands list/help file

**Comment by endrawes0** [comment]
I started this over the weekend, but it got out of hand. I am taking the time to redo the entire help section. I should finish it this weekend.

**Comment by lakinwecker** [comment]
Ok, I have updated the command to accept this format in #185

**Comment by lakinwecker** [comment]
I'm going to close this. we can continue the help message stuff in another issue.
