### ISSUE TITLE
Captains unable to assign alternates

### ISSUE THREAD

**Issue by tnan123** [endrawes0/Chesster#182]
somethingpretentious tried to assign an alt for The Sicilian Dragons today

He got the message: 
chessterBOT [03:28]  
Only the team's captain or a league moderator can do that.

**Comment by lakinwecker** [comment]
He tried to assign someone to the blunder bots, not to the Sicilian Dragons. Should any captain be able to assign to another team's member list?

**Comment by lakinwecker** [comment]
Closing.
