### ISSUE TITLE
Cheat detected result should be reported automatically

### ISSUE THREAD

**Issue by tnan123** [endrawes0/Chesster#250]
When chesster reports the score, if the game was a cheat detected game, the mods need to know to enforce our rules about such games. An automatic message would be very helpful.

I'm always afraid a game ends with cheat detection during a round without the mods not noticing.

**Comment by lakinwecker** [comment]
Fixed in https://github.com/endrawes0/Chesster/pull/274/commits/340b9bc04aa1caba236d613e3323d6d06f51e00c
