### ISSUE TITLE
@chesster Assign command

### ISSUE THREAD

**Issue by tnan123** [endrawes0/Chesster#262]
currently the assign command only works in #captains when it is used without "@chesster" to begin the command. It is confusing for captains.

Propose to make it consistent by requiring @chesster assign player .... blah blah

**Comment by lakinwecker** [comment]
This is fixed in this pull request: https://github.com/endrawes0/Chesster/pull/276 but the Travis build is failing for reasons that I don't have time to look into. It _might_ just be a temporary issue with Travis or some dependency website.    Remind me again in a few days to try this out again.

**Comment by lakinwecker** [comment]
Nevermind, it worked. :)
