### ISSUE TITLE
Carmel or snake case.... 

### ISSUE THREAD

**Issue by endrawes0** [endrawes0/Chesster#29]
Pick one and fix it.

We should be consistent going forward.

**Comment by endrawes0** [comment]
As discussed we should stick with camelCase from here on out. 

I already started converting everything, but I suspect we will have other commits that will take precedence.

This will have to wait until @lakinwecker finishes his refactoring.

**Comment by lakinwecker** [comment]
Closing for now, as we have mostly gotten this fixed. We can change other instances to camelCase as we see fit moving forward.
