### ISSUE TITLE
Chesster sends the correct rating when using the rating command only if you try it twice

### ISSUE THREAD

**Issue by kostasvl-github** [endrawes0/Chesster#293]
When for example you try the command : 
@chesster rating kostasvl , it will respond with my previous rating . Then I have to type again the command to see my current rating . It shows you your correct rating only if rating hasn't changed since last time you type the command but I haven't tested it to figure out .
Also maybe issue #271 should be moved here .

**Comment by lakinwecker** [comment]
I suspect this is fixed
