### ISSUE TITLE
The subscription list is incorrectly not including one's subscriptions from the previous season

### ISSUE THREAD

**Issue by mmixu** [endrawes0/Chesster#300]
Unable to view past seasons subscriptions, can view and manage this seasons
https://lichess4545.slack.com/archives/C0CSAFX27/p1558033020023300

**Comment by mmixu** [comment]
After the bot restart, the issue remains:
https://i.imgur.com/wAGRWyV.png

**Comment by lakinwecker** [comment]
Is this still happening?

**Comment by mmixu** [comment]
No, all good now

**Comment by lakinwecker** [comment]
Ok, great. Closing.
