### ISSUE TITLE
pairing command should give color information

### ISSUE THREAD

**Issue by Theino** [endrawes0/Chesster#35]
pairing currently gives "theino will play Pasternak(2019).  The game is unscheduled."

Color should be added. Ex: "theino will play **white against** Pasternak(2019).  The game is unscheduled."

**Comment by endrawes0** [comment]
Good idea
On May 9, 2016 11:46, Theino <notifications@github.com> wrote:pairing currently gives "theino will play Pasternak(2019).  The game is unscheduled."

Color should be added. Ex: "theino will play white against Pasternak(2019).  The game is unscheduled."

**Comment by endrawes0** [comment]
#41 fixes this
