### ISSUE TITLE
something is wrong with this gamelink

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#36]
/home/endrawes0/Chesster/chesster.js:1602
    if( details.winner && result.result == "1/2-1/2" ){
               ^

TypeError: Cannot read property 'winner' of undefined
    at validate_user_result (/home/endrawes0/Chesster/chesster.js:1602:16)
    at /home/endrawes0/Chesster/chesster.js:1637:28
    at IncomingMessage.<anonymous> (/home/endrawes0/Chesster/chesster.js:1533:17)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
/
~/Chesster /

8:51 PM] 
kirschwasser @cheesehead04 v @kirschwasser 0-1
[8:52 PM] 
lakinwecker hrmm
[8:53 PM] 
@cheesehead04 0-1 @kirschwasser
[8:53 PM] 
chessterBOT Sorry, you do not have permissin to update that pairing.
[8:53 PM] 
lakinwecker Try that format
[8:53 PM] 
not sure why yours didn't work
[8:54 PM] 
kirschwasser @cheesehead04 0-1 @kirschwasser
[8:54 PM] 
not working
[8:54 PM] 
lakinwecker huh
[8:54 PM] 
That is really odd
[8:55 PM] 
@kirschwasser: can you try it again?
[8:55 PM] 
kirschwasser @cheesehead04 0-1 @kirschwasser
[8:55 PM] 
lakinwecker There is a bug
[8:55 PM] 
it's trying to read your game link and failing, for some reason
[8:55 PM] 
I'll file a bug and ensure a mod updates it for you

**Comment by lakinwecker** [comment]
http://en.lichess.org/1CtQhqn2

**Comment by endrawes0** [comment]
Interesting. We had another case where the parsing method failed because slack gave us the link in markup. Maybe this is similar, but this link looks pretty normal to me.

**Comment by endrawes0** [comment]
Could be that this is related to the lichess API issues we were seeing.

**Comment by lakinwecker** [comment]
I suspect it was. Again, it's something we need to be able to deal with.  At the very least, chesster should detect it and ping the mods or developers

**Comment by endrawes0** [comment]
Agreed

**Comment by endrawes0** [comment]
The issue here was the lichess api - we did not handle it gracefully. 

I added some defensive programming and an error for if this happens again.

Fixed by #41
