### ISSUE TITLE
pairing without the @ fails now

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#37]
all of  ```pairing``` and ```pairing lakinwecker``` and ```pairing r-mena``` fail.  

```pairing @r-mena``` and ```pairing @lakinwecker``` are working

**Comment by lakinwecker** [comment]
Seems to be spotty.  Sometimes it works, sometimes it doesn't.

**Comment by endrawes0** [comment]
Saw your comments on slack. Do we think it was API issues?

**Comment by lakinwecker** [comment]
I think it was API issues, but we still need to deal with those somehow. I'm just unsure how to reproduce it.  

My best guess at the moment is that one of the servers in the lichess rotation was bad and when we hit it, we were getting invalid results.

**Comment by endrawes0** [comment]
I agree. As I said on slack, we should be coding defensively. At the very least, it should not cause an exception.

**Comment by endrawes0** [comment]
Turns out the issue here was the lichess api was unavailable. 

I added some protection for this kind of issue. Solved by #41
