### ISSUE TITLE
Make a "remind me for @endrawes0" command

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#44]
This command should store your preferences in a local data storage and ensure that whenever a gamelink is posted for the player you have posted, chesster will tell you that they are playing

**Comment by endrawes0** [comment]
do we want to do this? slack bot already can.

**Comment by lakinwecker** [comment]
slackbot can remind me when you start playing your next league game?  I want to be able to set it once, and have him remind me for everygame you play.

**Comment by endrawes0** [comment]
It can and it can't.

You can say

/remind me "lakin plays" at 05/21 14:00

**Comment by endrawes0** [comment]
It won't do this forever. You are correct it won't track players

**Comment by lakinwecker** [comment]
That's what I figured.  I have calendar software that can remind me of specific events at specific times. But I want the lazy-man's way to be reminded whenever a friend of mine is playing

**Comment by lakinwecker** [comment]
Btw, I'm also happy to have commands vetoed. if you don't want them in there. :)

**Comment by endrawes0** [comment]
I would if I really felt it was unnecessary. This clearly has value.

**Comment by Unihedro** [comment]
+1 for this. Mostly because Lichess's notification right now isn't delivering.

**Comment by endrawes0** [comment]
this can be consolidated into #81

**Comment by endrawes0** [comment]
duplicates #81
