### ISSUE TITLE
DM Team Captains whenever a teammate schedules a match

### ISSUE THREAD

**Issue by angborxley** [endrawes0/Chesster#50]
It's not overly difficult to keep an eye on the spreadsheet. But, since almost everything at this point can be managed from slack, it'd be nice to have an easy way for captains to keep track of if their team has scheduled or not. 

Maybe even a ping on Wednesday if a teammate hasn't scheduled yet. 

Thanks for what you're doing!

**Comment by lakinwecker** [comment]
:+1:

**Comment by endrawes0** [comment]
Agreed. Thanks for the suggestion.

**Comment by lakinwecker** [comment]
This will be partially covered by the work we are doing in #81

**Comment by lakinwecker** [comment]
@angborxley try this in a DM to chesster: ```tell me when a-game-is-scheduled in lonewolf for @lakinwecker```

**Comment by lakinwecker** [comment]
This is done.
