### ISSUE TITLE
Convert remaining @chesster commands to DM where appropriate.

### ISSUE THREAD

**Issue by endrawes0** [endrawes0/Chesster#51]
E.g. @chesster captains
Et Cetera...

**Comment by lakinwecker** [comment]
I believe that many of these have been done during the refactoring

**Comment by endrawes0** [comment]
Good. I'll take a look and see if there are any others that should move. If not, we can close this.

**Comment by endrawes0** [comment]
I am satisfied with @chesster's verbosity. I will close this.
