### ISSUE TITLE
Failed lichess api responses for alert user of reason for failure

### ISSUE THREAD

**Issue by endrawes0** [endrawes0/Chesster#66]
would avoid people repeating the same request over and over when they realize it is a rate limit issue.

**Comment by lakinwecker** [comment]
If we have any background tasks, then the background tasks could cause the refresh limit.  If the background causes it, then the user didn't cause it and it's a bit weird. 

Also, if we are caching all of the necessary lichess api call results, then we can just report the latest result and if it's during a 2 minute delay period, does it matter?

**Comment by endrawes0** [comment]
dont care any more. has not been much of an issue.
