### ISSUE TITLE
Fix the date parsing for formats that aren't working!

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#8]
For some reason it thought it was too late?

**Comment by lakinwecker** [comment]
Same with:  4/23 @ 18:00 GMT  Not working

**Comment by lakinwecker** [comment]
It's due to colons after the username. For example:

@lakin: vs @lakin 04/21 @ 21:30

won't work, but

@lakin vs @lakin 04/21 @ 21:30

will

**Comment by lakinwecker** [comment]
https://github.com/endrawes0/Chesster/pull/9 fixes this.

**Comment by endrawes0** [comment]
Similar issue maybe. 

I saw someone tried to post in the following format:

@player1 (white) v @player2 (black) mm/dd @ HH:MM

I'm thinking this failed for similar reasons. 

Do you want a new issue for this?

**Comment by lakinwecker** [comment]
https://github.com/endrawes0/Chesster/pull/10 fixes the white/black version

**Comment by lakinwecker** [comment]
Same issue or new issue is fine. I don't mind either way, so long as we are tracking it.

**Comment by lakinwecker** [comment]
captncarter vs Kimaga 17.00 GMT 27-04

Doesn't work.

**Comment by lakinwecker** [comment]
Sun 01.05.2016 @ 16:00 GMT
01.05.2016 @ 16:00 GMT
@steiger07 vs @matuiss2 5/1 @ 16:00 GMT

**Comment by lakinwecker** [comment]
@theknug: vs. @fradtheimpaler Sat. 4/30 at 14:00 GMT
@theknug - @fradtheimpaler saturday 30/4 14 GMT

**Comment by lakinwecker** [comment]
@greentiger v @crafty35a 16:00 on the 29th

**Comment by lakinwecker** [comment]
@iebrian vs @daveyjones01 Sunday may 8 1600 GMT

**Comment by endrawes0** [comment]
@lakinwecker you still need this? can I close it?

**Comment by lakinwecker** [comment]
Your call. There are still a few date formats that don't seem to work. We can keep working on it to fix it or just make people use the working formats.

I won't have time to work on it for a while, so it's unlikely to be "more fixed"

**Comment by endrawes0** [comment]
Tbh we are pretty flexible as is. Anything else is going to be more effort for the last 5% of cases.

Not worth it to me.
