### ISSUE TITLE
Make an event system with individual subscriptions

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#81]
```@chesster subscribe @endrawes game-start````

```@chesster unsubscribe @endrawes0 game-start```

```events.publish('game-start', target='endrawes0')```

```'game-scheduled'```

```'game-forfeited'```

**Comment by lakinwecker** [comment]
```@chesster subscribed @endrawes game-results```

**Comment by endrawes0** [comment]
`@chesster subscribe team winners game-results`

**Comment by lakinwecker** [comment]
We will also have to update the command to ensure that it can accept which league you are interested in as well.
```@chesster subscribe 45 game-results @endrawes0```

**Comment by lakinwecker** [comment]
```@chester tell me when a-new-game-starts in lonewolf for @endrawes0```

Documenting the final format I came up with.

```@chester tell <target> when <event> in <league> for <source>```

**Comment by endrawes0** [comment]
:thumbs_up:

**Comment by lakinwecker** [comment]
We can close this, right?

**Comment by endrawes0** [comment]
yes
