### ISSUE TITLE
Change callbacks in spreadsheet.js to use promises

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#88]
We are still using callbacks in a few places, notably in the spreadsheets.js - we should use promises as that means our exceptions will be caught and logged for us. 

Currently, trying to schedule an unknown pairing will take him down.

**Comment by lakinwecker** [comment]
This is one that I definitely think we can ignore until after we get the new website working.

**Comment by endrawes0** [comment]
heltour
