### ISSUE TITLE
When updating ratings, chesster should check for engine use

### ISSUE THREAD

**Issue by lakinwecker** [endrawes0/Chesster#89]
When updating ratings from lichess, we should probably have chesster also check to see if a particular user is marked as an engine users and inform the mods. I realize that engine use in casual and correspondence games might be allowed, but it's probably worth it for the league.

**Comment by endrawes0** [comment]
I'm on board

**Comment by endrawes0** [comment]
what do we do when found? alert mods I assume.

**Comment by lakinwecker** [comment]
Yes, alert the mods.

**Comment by lakinwecker** [comment]
The website now informs mods of engine marks. This is superfluous.
